-- MySQL Script generated by MySQL Workbench
-- 11/08/14 16:49:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema toystore
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `toystore` ;

-- -----------------------------------------------------
-- Schema toystore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toystore` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `toystore` ;

-- -----------------------------------------------------
-- Table `toystore`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`User` ;

CREATE TABLE IF NOT EXISTS `toystore`.`User` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `BillingAddress` VARCHAR(45) NULL,
  `ShippingAddress` VARCHAR(45) NULL,
  `Password` VARCHAR(255) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toystore`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`Category` ;

CREATE TABLE IF NOT EXISTS `toystore`.`Category` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toystore`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`Order` ;

CREATE TABLE IF NOT EXISTS `toystore`.`Order` (
  `Id` INT NOT NULL,
  `OrderDate` DATE NOT NULL,
  `Total` DOUBLE NULL,
  `Status` VARCHAR(45) NOT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Order_UserId_FK_idx` (`UserId` ASC),
  CONSTRAINT `Order_UserId_FK`
    FOREIGN KEY (`UserId`)
    REFERENCES `toystore`.`User` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toystore`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`Product` ;

CREATE TABLE IF NOT EXISTS `toystore`.`Product` (
  `Id` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Price` VARCHAR(45) NULL,
  `Inventory` VARCHAR(45) NULL,
  `Picture` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toystore`.`OrderItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`OrderItem` ;

CREATE TABLE IF NOT EXISTS `toystore`.`OrderItem` (
  `Id` INT NOT NULL,
  `OrderId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` DOUBLE NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `OrderItem_Order_idx` (`OrderId` ASC),
  INDEX `OrderItem_Product_idx` (`ProductId` ASC),
  CONSTRAINT `OrderItem_Order`
    FOREIGN KEY (`OrderId`)
    REFERENCES `toystore`.`Order` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OrderItem_Product`
    FOREIGN KEY (`ProductId`)
    REFERENCES `toystore`.`Product` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toystore`.`ProductToCategory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toystore`.`ProductToCategory` ;

CREATE TABLE IF NOT EXISTS `toystore`.`ProductToCategory` (
  `ProductId` INT NOT NULL,
  `CategoryId` INT NOT NULL,
  PRIMARY KEY (`ProductId`, `CategoryId`),
  INDEX `PTC_CategoryId_idx` (`CategoryId` ASC),
  CONSTRAINT `PTC_ProductId`
    FOREIGN KEY (`ProductId`)
    REFERENCES `toystore`.`Product` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PTC_CategoryId`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `toystore`.`Category` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
